<?php

use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Render\Element;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function btj_scrap_group_view_alter(array &$build,
  Drupal\Core\Entity\EntityInterface $entity,
  \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {

  if (!empty($build['field_scrap_libraries'])) {
    foreach (Element::children($build['field_scrap_libraries']) as $key) {
      $libraryUrl = Url::fromUserInput("/scrap/" . $entity->id() . '/library');
      $build['field_scrap_libraries'][$key]['#url'] = $libraryUrl;
    }
  }
  if (!empty($build['field_scrap_events'])) {
    foreach (Element::children($build['field_scrap_events']) as $key) {
      $libraryUrl = Url::fromUserInput("/scrap/" . $entity->id() . '/events');
      $build['field_scrap_events'][$key]['#url'] = $libraryUrl;
    }
  }
  if (!empty($build['field_scrap_news'])) {
    foreach (Element::children($build['field_scrap_events']) as $key) {
      $libraryUrl = Url::fromUserInput("/scrap/" . $entity->id() . '/news');
      $build['field_scrap_news'][$key]['#url'] = $libraryUrl;
    }
  }
}
