<?php
/**
 * @file
 * Main module hooks implementation.
 */

use Drupal\Core\Url;
use Drupal\Core\Render\Element;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

use \Drupal\group\Entity\GroupInterface;
use \Drupal\btj_scrapper\Controller\ScrapController;

/**
 * Implements hook_form_alter().
 */
function btj_scrapper_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['node_ding_event_form', 'node_ding_news_form', 'node_ding_library_form'])) {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'btj_node_add_form_submit';
      }
    }
  }
}

/**
 * Add municipality reference to node field on save.
 */
function btj_node_add_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $nid = $form_state->get('nid');
  if (empty($nid)) {
    return;
  }

  // TODO: This should be refactored towards a form_validate routine.
  // So no value is forced unless the user explicitly sets one, or the default
  // is used.
  $account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  $municipality = $account->get('field_municipality_ref')
    ->first()
    ->get('entity')
    ->getTargetIdentifier();

  if (!$municipality) {
    \Drupal::messenger()->addMessage(t('You don\'t have any municipality ownership assigned. Please contact site administrator.', MessengerInterface::TYPE_WARNING));
  }
  $node = \Drupal\node\Entity\Node::load($nid);
  $node->set('field_municipality', $municipality);

  // TODO: This should be refactored to a form_alter routine.
  // So the field is pre-populated with a municipality value.
  // Currently, this invokes an unnecessary update request towards mobilesearch
  // since mobilesearch module track entity update hooks to perform storage update.
  // Looks like an action "made in the dark" - i.e. the node is manipulated
  // during save, without any knowledge to the user. This invalidates the fact
  // that a user can assign a different municipality manually.
  $node->save();
}

/**
 * Implements hook_entity_delete().
 */
function btj_scrapper_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  \Drupal::database()
    ->delete('btj_scrapper_relations')
    ->condition('entity_id', $entity->id())
    ->execute();
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * Prepare queue on group creation.
 */
function btj_scrapper_group_update(GroupInterface $group) {
  $controller = new ScrapController();
  $bundles = ['library', 'news', 'event'];
  foreach ($bundles as $bundle) {
    $controller->prepare($group, $bundle);
  }
}

/**
 * Implements hook_cron().
 */
function btj_scrapper_cron() {
  \Drupal::logger('btj_scrapper')
    ->notice('Move prepared items from the relation table to the queue to be scrapped.');

  // Move items to queue
  $rows = \Drupal::database()->select('btj_scrapper_relations', 'bsr')
    ->fields('bsr')
    ->condition('bsr.status', 0)
    ->orderBy('weight', 'DESC')
    ->range(0, 100)
    ->execute()
    ->fetchAll();

  /** @var QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  foreach ($rows as $row) {
    $item = new \stdClass();
    $item->gid = $row->gid;
    $item->entity_id = $row->entity_id;
    $item->type = $row->type;
    $item->bundle = $row->bundle;
    $item->link = $row->item_url;
    $item->uid = $row->uid;

    /** @var QueueInterface $queue */
    $queue = $queue_factory->get('btj_scrap_' . $row->bundle);
    $queue->createItem($item);

    // Update relations status.
    $controller = new ScrapController();
    $controller->updateRelations($row->item_url, $row->bundle, $row->entity_id, $row->uid, $row->gid, $row->type, 1);
  }

}
